# Generated by Django 3.1.2 on 2020-10-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201010_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Student',
            new_name='student',
        ),
    ]
