# Generated by Django 3.1.2 on 2020-12-12 17:17

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201212_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to=myapp.models.Student.img_path),
        ),
    ]
